export { SpecificArticle } from './ui/SpecificArticle/SpecificArticle'
export type { ArticleSchema } from './model/types/articleSchema'
export type { Article } from './model/types/article'
export { ArticleType } from './model/types/article'
export { articleReducer } from './model/slices/articleSlice'
export { getArticleData } from './model/selectors/getArticleData/getArticleData'
export { ArticlesList } from './ui/ArticlesList/ArticlesList'
