name: Education-project actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build an app (production)
        run: npm run build:prod
        if: always()

      - name: Check unit tests
        run: npm run test:unit
        if: always()

      - name: Start style linter
        run: npm run lint:scss
        if: always()

      - name: Start typescript linter
        run: npm run lint:ts
        if: always()

      - name: Build storybook
        run: npm run storybook:build
        if: always()

      - name: Check regression tests
        run: npm run test:regr:ci
        if: always()
