name: Education-project actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.4.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build an app (production)
        run: webpack --env mode='production'

      - name: Check unit tests
        run: jest --config ./config/jest/jest.config.ts

      - name: Start style linter
        run: npx stylelint \"**/*.scss\"

      - name: Start typescript linter
        run: eslint \"**/*.{ts, tsx}\"
